# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: Default

steps:
- script: | 
    c:\LDRA_Toolsuite_C_CPP_10.0.3\contbbuildimport -build_cmd="mingw32-make bzip2" -startin_dir=%CD% -build -quit
    c:\LDRA_Toolsuite_C_CPP_10.0.3\contestbed libbz2.a.btf /11234q
    mkdir TestResults
    copy C:\LDRA_Workarea_C_CPP_10.0.3\libbz2.a_tbwrkfls\libbz2.a_reports\libbz2.a.rps.htm TestResults
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'


- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'C:\LDRA_Workarea_C_CPP_10.0.3\libbz2.a_tbwrkfls\libbz2.a_reports\'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)'
        artifact: 'zip'
        publishLocation: 'pipeline'